# Menu
menu:
  主页: /
  分类: /categories
  标签: /tags
  归档: /archives
rss: /atom.xml


# Miscellaneous
favicon: /images/avatar.jpg
brand: /images/avatar.jpg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: false
  video: false
  image: true
  videoPath: /images/ocean/
  path: /images/ocean/
  brand: /images/avatar.jpg
  bgImage: /images/background.jpg

# Content
excerpt_link: 阅读全文...

# Tags
show_count: true

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: true # true
  clientID: 4f6f2101bdbd8c5b014d # GitHub Application Client ID
  clientSecret: 2b5d1579e2dd283560a14d8dbd463e76038b3e7d # Client Secret
  repo: ittalk-issues # Repository name
  owner: jm-bai # GitHub ID
  admin: jm-bai # GitHub ID

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId: 
  appKey: 
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...' 